# Graph Mining

# Sparse Matrices

In this lab, you will learn to use sparse matrices.

In [1]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [2]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [3]:
X_dense

array([[2, 1, 0, 2, 2],
       [1, 0, 2, 2, 0],
       [1, 1, 2, 2, 0],
       [1, 0, 0, 0, 2],
       [0, 2, 0, 1, 1],
       [0, 1, 2, 1, 1],
       [0, 0, 1, 2, 0],
       [2, 0, 0, 2, 1],
       [0, 0, 1, 2, 1],
       [2, 2, 1, 2, 0]])

In [4]:
X_csr = sparse.csr_matrix(X_dense)

In [5]:
X_csr.shape

(10, 5)

In [6]:
# number of non-zeros
X_csr.nnz

32

The data structure consists of 3 vectors:

In [7]:
X_csr.indices

array([0, 1, 3, 4, 0, 2, 3, 0, 1, 2, 3, 0, 4, 1, 3, 4, 1, 2, 3, 4, 2, 3,
       0, 3, 4, 2, 3, 4, 0, 1, 2, 3], dtype=int32)

In [8]:
X_csr.indptr

array([ 0,  4,  7, 11, 13, 16, 20, 22, 25, 28, 32], dtype=int32)

In [9]:
X_csr.data

array([2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 1, 2, 2, 1, 2])

## To do

* Can you find the number of non-zeros from these 3 vectors?
* What about the shape of the matrix?

In [10]:
X_csr.nnz

32

In [11]:
X_csr.shape

(10, 5)

In [12]:
len(X_csr.indptr)

11

In [13]:
# number of non-zero entries
X_csr.indices.shape

(32,)

In [14]:
# shape of the matrix
(len(X_csr.indptr) - 1)

10

In [15]:
(len(X_csr.indptr) // 2)

5

**ANSWER**

1 - Yes, we can use the shape of X_csr indices as it stores the indices of non-zero elements.

2 - No, we can use indptr - 1 to get the number of rows, but we cannot retrieve number of columns.

## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [16]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [17]:
X_dense

array([[0, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 1]])

In [18]:
a = np.ones(n_col, dtype=int)

In [19]:
b = X.dot(a)

In [20]:
b

array([1, 2, 2, 2, 2, 3, 4, 1, 1, 2])

In [21]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [22]:
b

array([3, 7, 4, 6])

In [23]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [24]:
A

array([[1, 1],
       [0, 0],
       [1, 0],
       [1, 0]])

In [25]:
B

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [2, 0],
       [3, 1],
       [0, 0],
       [1, 0],
       [2, 1]])

In [26]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [27]:
B

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (10, 2)>

In [28]:
B.toarray()

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [2, 0],
       [3, 1],
       [0, 0],
       [1, 0],
       [2, 1]])

In [29]:
X.T.dot(X)

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 16 stored elements and shape (4, 4)>

In [30]:
X.dot(X.T)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 78 stored elements and shape (10, 10)>

In [31]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [32]:
X_dense

array([[2, 1, 2, 2, 2],
       [0, 0, 2, 0, 1],
       [0, 1, 0, 2, 0],
       [0, 1, 0, 0, 1],
       [2, 0, 2, 1, 2],
       [1, 0, 1, 2, 2],
       [1, 0, 2, 1, 1],
       [2, 0, 0, 0, 0],
       [1, 2, 2, 1, 2],
       [1, 0, 1, 1, 1]])

In [33]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 33 stored elements and shape (10, 5)>

In [34]:
Y = X > 1

In [35]:
Y

<Compressed Sparse Row sparse matrix of dtype 'bool'
	with 16 stored elements and shape (10, 5)>

In [36]:
Y.dot(np.ones(n_col, dtype=int))

array([4, 1, 1, 0, 3, 2, 1, 1, 3, 0])

In [37]:
Y.dot(np.ones(n_col, dtype=bool))

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
       False])

In [38]:
Z = 2 * X + 5 * Y

In [39]:
Z

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 33 stored elements and shape (10, 5)>

In [40]:
Z.power(2)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 33 stored elements and shape (10, 5)>

## To do

Consider the following matrix:

In [41]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

In [42]:
def euc_norm(X):
  norm = np.zeros((len(X.indptr)-1))
  for (i,_) in enumerate(X.indptr):
    if (i == (len(X.indptr)-1)): # break at last line
      break
    sum = 0
    for j in range(X.indptr[i],X.indptr[i+1]):
      sum += (X.data[j]**2)
    norm[i] = sum
    norm = np.sqrt(norm)
  return norm

print(euc_norm(X))

[1.00000198 1.00000419 1.00000614 1.00001676 1.00001058 1.00004912
 1.00004231 1.00019648 1.         1.00121407 1.00157295 1.
 1.00975393 1.01637831 1.02189715 1.05758973 1.09050773 1.18920712
 1.49534878 1.41421356]


## Slicing

Sparse matrices can be sliced like numpy arrays.

In [43]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [44]:
X = sparse.csr_matrix(X_dense)

In [45]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 32 stored elements and shape (10, 5)>

In [46]:
indices = [2, 5, 6]

In [47]:
X[indices]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (3, 5)>

In [48]:
X[:, [1, 3]]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14 stored elements and shape (10, 2)>

## To do

Consider the following matrix:

In [49]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

In [51]:
norms = euc_norm(X)
print(norms)

#select 5 largest
biggest = np.argsort(norms)[-5:]
print(biggest)

[1.0000021  1.00000474 1.00001297 1.00002486 1.00004784 1.00009143
 1.0001653  1.0003222  1.00070591 1.00132316 1.00297759 1.00486513
 1.01135449 1.02479854 1.04427378 1.08596668 1.23153675 1.45421543
 2.08779763 3.46410162]
[15 16 17 18 19]


## DIAG format

In [52]:
D = sparse.diags(np.arange(10))

In [53]:
D

<DIAgonal sparse matrix of dtype 'float64'
	with 10 stored elements (1 diagonals) and shape (10, 10)>

In [56]:
D.data

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
D.nnz

10

In [57]:
D = sparse.csr_matrix(D)

In [58]:
D.data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
D.nnz

9

In [60]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [61]:
D.dot(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 17 stored elements and shape (10, 4)>

In [62]:
D = sparse.diags(np.ones(4))

In [63]:
X.dot(D)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 20 stored elements and shape (10, 4)>

## To do

Consider the following matrix:

In [ ]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero).

In [66]:
def normalize(X):
    X = X.astype(float)

    row_sums = np.array(X.sum(axis=1)).flatten()
    row_sums[row_sums == 0] = 1  # avoid division by zero

    D_inv = sparse.diags(1 / row_sums)

    return D_inv @ X
print(normalize(X))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (10, 4)>
  Coords	Values
  (2, 1)	1.0
  (3, 3)	1.0
  (4, 3)	1.0
  (7, 0)	1.0


## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [67]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [68]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [69]:
X_coo

<COOrdinate sparse matrix of dtype 'int64'
	with 3 stored elements and shape (5, 5)>

In [70]:
X_coo.row

array([1, 4, 2], dtype=int32)

In [71]:
X_coo.col

array([2, 0, 2], dtype=int32)

In [72]:
X_coo.data

array([1, 2, 3])

You can change the format:

In [73]:
X_csr = X_coo.tocsr()

In [74]:
X_csr

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (5, 5)>

In [75]:
X_csr.indices

array([2, 2, 0], dtype=int32)

In [76]:
X_csr.indptr

array([0, 0, 1, 2, 2, 3], dtype=int32)

In [77]:
X_csr.data

array([1, 3, 2])

In [78]:
X_csr.tocoo()

<COOrdinate sparse matrix of dtype 'int64'
	with 3 stored elements and shape (5, 5)>

You can directly load a CSR matrix from COO format:

In [79]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [80]:
X_csr

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (5, 5)>

Duplicate entries are not summed by default in the COO format (also in the CSR format in the last version of Scipy):

In [81]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [82]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [83]:
X_coo

<COOrdinate sparse matrix of dtype 'int64'
	with 4 stored elements and shape (5, 5)>

In [84]:
X_coo.nnz

4

In [85]:
X_coo.toarray()

array([[0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0]])

In [86]:
X_coo.dot(np.ones(5, dtype=int))

array([0, 5, 3, 0, 2])

In [87]:
X_coo.data

array([1, 2, 3, 4])

In [88]:
X_coo.sum_duplicates()

In [89]:
X_coo

<COOrdinate sparse matrix of dtype 'int64'
	with 3 stored elements and shape (5, 5)>

In [90]:
X_coo.data

array([5, 3, 2])

If data contain some zeros, these are coded as non-zeros by default:

In [91]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 0]

In [92]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [93]:
X_csr

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (5, 5)>

In [94]:
X_csr.eliminate_zeros()

In [95]:
X_csr

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (5, 5)>

## To do

Consider the following matrix:

In [96]:
row = [1, 1, 2, 4, 2, 1]
col = [2, 2, 2, 0, 2, 2]
data = [1, 2, 3, 4, 0, 2]

X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))
X_csr.sum_duplicates()

* What is the number of non-zeros?
* Check your answer using ``nnz``.

there are 3 non-zero entries

In [97]:
X_csr.nnz

3